[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Witsense ugv"
author = "Witsense Project Developers"
maintainer = "witsense project Project Developers"
description= "Isaac Lab for Witsense UGV"
repository = "https://github.com/WitsenseAI/so101-custom-training.git"
keywords = ["extension", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}

[[python.module]]
name = "witsense_ugv"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
apt_deps = ["libx264-dev"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"